написал три функции
htmlacademy-univer-javascript-1/88327-kekstagram-5 pull request #3
Opened 2024-11-28 19:03 UTC by Tuzemecc

2024-12-01 07:10 UTC, dimohqa requested changes

2024-12-01 07:10 UTC, dimohqa commented on js/function.js
> +  str = str.replaceAll(/\s/g, '').toLowerCase();
Лучше всего избегать мутаций аргументов функций. Что это значит? Лучше напрямую не изменять аргументы функции (в твоем случае, str)
Почему?

Ухудшается читаемость кода. Функция не возвращает значение, а изменяет один из входящих параметров, становится непонятно, как ее использовать.
Ошибки, вызванные случайными изменениями, сложно заметить и отследить.
Сейчас у тебя довольно простая функция и проблемы нет. Когда она станет больше, то запросто можно не заметить как сначала ты поменял аргмуент, а потом используешь его и ожидаешь, что он будет не изменен. А если таких изменений аргумента будет несколько...?)

Поэтому в твоем случае лучше завести отдельную переменную через let/const.

2024-12-01 07:10 UTC, dimohqa commented on js/function.js
> +  str = str.replaceAll(/\s/g, '').toLowerCase();
В других функциях тоже самое

2024-12-01 14:42 UTC, Tuzemecc commented on js/function.js
> +  str = str.replaceAll(/\s/g, '').toLowerCase();
исправил

2024-12-02 07:08 UTC, dimohqa requested changes

2024-12-02 07:08 UTC, dimohqa commented on js/function.js
> +  normalizedStr = str.replaceAll(/\s/g, '').toLowerCase();
А зачем тебе объявлять сначала пустую строку, а потом туда записывать другое значение? Ты можешь делать это сразу

2024-12-02 07:48 UTC, Tuzemecc commented on js/function.js
> +  normalizedStr = str.replaceAll(/\s/g, '').toLowerCase();
поправил

2024-12-03 09:28 UTC, merged