5.14. Модуляция
htmlacademy-univer-javascript-1/88327-kekstagram-5 pull request #5
Opened 2024-12-04 12:04 UTC by Tuzemecc

2024-12-09 05:36 UTC, dimohqa requested changes

2024-12-09 05:36 UTC, dimohqa commented on js/config.js
> +mock.names = [
Ты опять инициализируешь переменную пустым значением, а потом ее наполняешь.

Вот [тут](https://learn.javascript.ru/variables#analogiya-iz-zhizni) хорошая аналогия. Ты создаешь "коробку", которая по сути является твоей переменной(первое действие `const mock = {}`). После чего кладешь в эту коробку что-то, в твоем случае имена (`mock.names = [...]`). Получается вместо одного действия - создать коробку с именами, ты делаешь два - создать коробку, положить туда имена.

2024-12-09 16:09 UTC, Tuzemecc commented on js/config.js
> +mock.names = [
май бэд.
Писал это еще до твоих комментариев и не переделал после. Сорян, исправился.

2024-12-10 08:00 UTC, merged

2024-12-10 08:01 UTC, dimohqa approved these changes